const SET_CUSTOMER_DATA = 'madeByHands/user/SET_CUSTOMER_DATA';
const SET_CUSTOMER_LOADING = 'madeByHands/user/SET_CUSTOMER_LOADING';
const SET_CUSTOMER_DATA_MSG = 'madeByHands/user/SET_CUSTOMER_DATA_MSG';

export default {
  SET_CUSTOMER_DATA,
  SET_CUSTOMER_LOADING,
  SET_CUSTOMER_DATA_MSG,
};
